name: Docker

on:
  workflow_dispatch:
    inputs:
      tagInput:
        description: 'Tag'
        required: true

  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine version tag
        id: version-tag
        run: |
          if [ -n "${{ github.event.inputs.tagInput }}" ]; then
            echo "tag=${{ github.event.inputs.tagInput }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ieasybooks/tafrigh:latest
            ghcr.io/ieasybooks/tafrigh:${{ steps.version-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Wit image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            DEPS=wit
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ieasybooks/tafrigh-wit:latest
            ghcr.io/ieasybooks/tafrigh-wit:${{ steps.version-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push Whisper image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            DEPS=whisper
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ieasybooks/tafrigh-whisper:latest
            ghcr.io/ieasybooks/tafrigh-whisper:${{ steps.version-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
